name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1'
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install
      run: npm install
    - name: Build
      run: npx shadow-cljs release :frontend
    - name: Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "public"
